kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc-prod
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem